version: '3.8'

services:
  aidetective:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aidetective
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database.db:/app/backend/database.db
    env_file: ".env"
    restart: unless-stopped
