version: '3.8'

services:
  aidetective:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aidetective
    ports:
      - "3000:3000"
    env_file: ".env"
    restart: unless-stopped
